# Generated by Django 5.2.9 on 2026-09-02 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevetryxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddIndex(
            model_name='devetryxevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='core_devetr_event_t_219a32_idx'),
        ),
        migrations.AddIndex(
            model_name='devetryxevent',
            index=models.Index(fields=['session_id', 'timestamp'], name='core_devetr_session_81f5c9_idx'),
        ),
    ]
